# Generated by Django 4.0.2 on 2022-03-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_rename_task_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rejectdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
