# Generated by Django 4.0.2 on 2022-03-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_project_rejectdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_taskassign',
            name='extension',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
