# Generated by Django 4.0.2 on 2022-03-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_project_taskassign_extension'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leave',
            new_name='applyleave',
        ),
    ]
