# Generated by Django 4.0.2 on 2022-03-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_rename_leave_applyleave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='applyleave',
            new_name='leave',
        ),
    ]
