# Generated by Django 4.0.2 on 2022-03-04 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_rename_applyleave_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester_status',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tester_statussubtask', to='base_app.project_taskassign'),
        ),
    ]
